### ISSUE TITLE
Create Wireframe

### ISSUE THREAD

**Issue by Evermuniz** [carlystahelidavis/java-chips#6]
Create wireframe for application layout

**Comment by nisha4r** [comment]
![Image](https://user-images.githubusercontent.com/125222406/229009900-d40bf257-f4b5-4cb8-867a-b68f09ba778a.png)
![Image](https://user-images.githubusercontent.com/125222406/229009901-fa14a56e-2ff8-44e5-8e56-8ac7ba463f07.png)
![Image](https://user-images.githubusercontent.com/125222406/229009903-11f576a0-b4d2-4891-95c2-9445268fbb5b.png)
![Image](https://user-images.githubusercontent.com/125222406/229009902-6865c6d1-2d42-4ff0-aee2-1ade390f4093.png)
